markdown: kramdown
highlighter: pygments
safe: false
paginate: 10
paginate_path: "page:num"
permalink: /posts/:title.html
exclude:
  - README.md

name: Shuai ZHU
host: szhu57.github.com
baseurl: http://szhu57.xyz/
desc: I'm still learning
avatar: https://raw.githubusercontent.com/szhu57/szhu57.github.io/master/img/site/logo.png

custom:
    category:
        knowledge: knowledge
        database: database
        technique: technique
        others: others

    categories:
      - name:  knowledge
        title: knowledge

      - name:  database
        title: database

      - name: technique
        title: technique

      - name: others
        title: others

meta:
    author:
        name: Shuai ZHU
        email: szhu57.outlook.com
        disqus: szhu                             # Disqus缩略标识
        gcse: 017273734144320215856:r-n1xry8woo     # Google自定义搜索标识ID
        github: szhu57                              # GitHub账号
        gravatar: 48b4b2d677d28780288ab93737230019  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

